'use strict';(function(J,F){"function"===typeof define&&define.amd?define(F):"object"===typeof exports?module.exports=F(require,exports,module):J.Tether=F()})(this,function(J,F,M){(function(){var p,v,l,u,n,G,x,z,y,k,g,c,e={}.hasOwnProperty,s=[].indexOf||function(b){for(var a=0,m=this.length;a<m;a++)if(a in this&&this[a]===b)return a;return-1},d=[].slice;null==this.Tether&&(this.Tether={modules:[]});g=function(){var b;b=0;return function(){return b++}}();c={};x=function(b){var a,m,q;q=b._tetherZeroElement;
null==q&&(q=b.createElement("div"),q.setAttribute("data-tether-id",g()),n(q.style,{top:0,left:0,position:"absolute"}),b.body.appendChild(q),b._tetherZeroElement=q);a=q.getAttribute("data-tether-id");if(null==c[a]){c[a]={};q=q.getBoundingClientRect();for(m in q)b=q[m],c[a][m]=b;l(function(){return c[a]=void 0})}return c[a]};n=function(b){var a,m,q,c,f,d;null==b&&(b={});a=[];Array.prototype.push.apply(a,arguments);d=a.slice(1);c=0;for(f=d.length;c<f;c++)if(a=d[c])for(m in a)e.call(a,m)&&(q=a[m],b[m]=
q);return b};y=function(b,a){var m,q,c,f,e;if(null!=b.classList){f=a.split(" ");e=[];q=0;for(c=f.length;q<c;q++)m=f[q],m.trim()&&e.push(b.classList.remove(m));return e}m=G(b).replace(new RegExp("(^| )"+a.split(" ").join("|")+"( |$)","gi")," ");return k(b,m)};v=function(b,a){var m,c,e,f,d;if(null!=b.classList){f=a.split(" ");d=[];c=0;for(e=f.length;c<e;c++)m=f[c],m.trim()&&d.push(b.classList.add(m));return d}y(b,a);m=G(b)+(" "+a);return k(b,m)};z=function(b,a){return null!=b.classList?b.classList.contains(a):
(new RegExp("(^| )"+a+"( |$)","gi")).test(G(b))};G=function(b){return b.className instanceof SVGAnimatedString?b.className.baseVal:b.className};k=function(b,a){return b.setAttribute("class",a)};u=[];l=function(b){return u.push(b)};p=function(){function b(){}b.prototype.on=function(a,b,c,e){var f;null==e&&(e=!1);null==this.bindings&&(this.bindings={});null==(f=this.bindings)[a]&&(f[a]=[]);return this.bindings[a].push({handler:b,ctx:c,once:e})};b.prototype.once=function(a,b,c){return this.on(a,b,c,
!0)};b.prototype.off=function(a,b){var c,e;if(null!=(null!=(c=this.bindings)?c[a]:void 0)){if(null==b)return delete this.bindings[a];c=0;for(e=[];c<this.bindings[a].length;)this.bindings[a][c].handler===b?e.push(this.bindings[a].splice(c,1)):e.push(c++);return e}};b.prototype.trigger=function(){var a,b,c,e,f,g,k;c=arguments[0];a=2<=arguments.length?d.call(arguments,1):[];if(null!=(b=this.bindings)&&b[c]){f=0;for(k=[];f<this.bindings[c].length;)g=this.bindings[c][f],e=g.handler,b=g.ctx,g=g.once,e.apply(null!=
b?b:this,a),g?k.push(this.bindings[c].splice(f,1)):k.push(f++);return k}};return b}();this.Tether.Utils={getScrollParent:function(b){var a,c,e;a=getComputedStyle(b).position;if("fixed"===a)return b;for(;b=b.parentNode;){try{c=getComputedStyle(b)}catch(d){}if(null==c||/(auto|scroll)/.test(c.overflow+c.overflowY+c.overflowX)&&("absolute"!==a||"relative"===(e=c.position)||"absolute"===e||"fixed"===e))return b}return document.body},getBounds:function(b){var a,c,e,d,f;b===document?(c=document,b=document.documentElement):
c=b.ownerDocument;e=c.documentElement;a={};f=b.getBoundingClientRect();for(d in f)b=f[d],a[d]=b;d=x(c);a.top-=d.top;a.left-=d.left;null==a.width&&(a.width=document.body.scrollWidth-a.left-a.right);null==a.height&&(a.height=document.body.scrollHeight-a.top-a.bottom);a.top-=e.clientTop;a.left-=e.clientLeft;a.right=c.body.clientWidth-a.width-a.left;a.bottom=c.body.clientHeight-a.height-a.top;return a},getOffsetParent:function(b){return b.offsetParent||document.documentElement},extend:n,addClass:v,removeClass:y,
hasClass:z,updateClasses:function(b,a,c){var e,d,f;d=0;for(f=c.length;d<f;d++)e=c[d],0>s.call(a,e)&&z(b,e)&&y(b,e);f=[];c=0;for(d=a.length;c<d;c++)e=a[c],z(b,e)?f.push(void 0):f.push(v(b,e));return f},defer:l,flush:function(){var b,a;for(a=[];b=u.pop();)a.push(b());return a},uniqueId:g,Evented:p,getScrollBarSize:function(){var b,a,c;b=document.createElement("div");b.style.width="100%";b.style.height="200px";a=document.createElement("div");n(a.style,{position:"absolute",top:0,left:0,pointerEvents:"none",
visibility:"hidden",width:"200px",height:"150px",overflow:"hidden"});a.appendChild(b);document.body.appendChild(a);c=b.offsetWidth;a.style.overflow="scroll";b=b.offsetWidth;c===b&&(b=a.clientWidth);document.body.removeChild(a);a=c-b;return{width:a,height:a}}}}).call(this);(function(){var p,v,l,u,n,G,x,z,y,k,g,c,e,s,d,b,a,m,q,A,f,C,w,h,t,r,K=[].slice,E=function(a,b){return function(){return a.apply(b,arguments)}};if(null==this.Tether)throw Error("You must include the utils.js file before tether.js");
u=this.Tether;r=u.Utils;d=r.getScrollParent;c=r.getBounds;e=r.getOffsetParent;k=r.extend;n=r.addClass;f=r.removeClass;h=r.updateClasses;y=r.defer;g=r.flush;s=r.getScrollBarSize;t=function(a,b,c){null==c&&(c=1);return a+c>=b&&b>=a-c};w=function(){var a,b,c,e,D;a=document.createElement("div");D=["transform","webkitTransform","OTransform","MozTransform","msTransform"];c=0;for(e=D.length;c<e;c++)if(b=D[c],void 0!==a.style[b])return b}();C=[];A=function(){var a,b,c;b=0;for(c=C.length;b<c;b++)a=C[b],a.position(!1);
return g()};b=function(){var a;return null!=(a="undefined"!==typeof performance&&null!==performance?"function"===typeof performance.now?performance.now():void 0:void 0)?a:+new Date};(function(){var a,c,e,I,D,d,f,g,k;I=e=c=null;D=function(){if(null!=e&&16<e)e=Math.min(e-16,250),I=setTimeout(D,250);else if(!(null!=c&&10>b()-c))return null!=I&&(clearTimeout(I),I=null),c=b(),A(),e=b()-c};g=["resize","scroll","touchmove"];k=[];d=0;for(f=g.length;d<f;d++)a=g[d],k.push(window.addEventListener(a,D));return k})();
p={center:"center",left:"right",right:"left"};v={middle:"middle",top:"bottom",bottom:"top"};l={top:0,left:0,middle:"50%",center:"50%",bottom:"100%",right:"100%"};z=function(a,b){var c,e;c=a.left;e=a.top;"auto"===c&&(c=p[b.left]);"auto"===e&&(e=v[b.top]);return{left:c,top:e}};x=function(a){var b,c;return{left:null!=(b=l[a.left])?b:a.left,top:null!=(c=l[a.top])?c:a.top}};G=function(){var a,b,c,e,D,d;b=1<=arguments.length?K.call(arguments,0):[];c={top:0,left:0};D=0;for(d=b.length;D<d;D++)a=b[D],e=a.top,
a=a.left,"string"===typeof e&&(e=parseFloat(e,10)),"string"===typeof a&&(a=parseFloat(a,10)),c.top+=e,c.left+=a;return c};a=function(a,c){"string"===typeof a.left&&-1!==a.left.indexOf("%")&&(a.left=parseFloat(a.left,10)/100*c.width);"string"===typeof a.top&&-1!==a.top.indexOf("%")&&(a.top=parseFloat(a.top,10)/100*c.height);return a};m=q=function(a){a=a.split(" ");return{top:a[0],left:a[1]}};r=function(){function b(a){this.position=E(this.position,this);var c,e,d,f;C.push(this);this.history=[];this.setOptions(a,
!1);d=u.modules;c=0;for(e=d.length;c<e;c++)a=d[c],null!=(f=a.initialize)&&f.call(this);this.position()}b.modules=[];b.prototype.getClass=function(a){var b,c;return null!=(b=this.options.classes)&&b[a]?this.options.classes[a]:!1!==(null!=(c=this.options.classes)?c[a]:void 0)?this.options.classPrefix?""+this.options.classPrefix+"-"+a:a:""};b.prototype.setOptions=function(a,b){var c,e,f,g;this.options=a;null==b&&(b=!0);c=this.options=k({offset:"0 0",targetOffset:"0 0",targetAttachment:"auto auto",classPrefix:"tether"},
this.options);this.element=c.element;this.target=c.target;this.targetModifier=c.targetModifier;"viewport"===this.target?(this.target=document.body,this.targetModifier="visible"):"scroll-handle"===this.target&&(this.target=document.body,this.targetModifier="scroll-handle");g=["element","target"];e=0;for(f=g.length;e<f;e++){c=g[e];if(null==this[c])throw Error("Tether Error: Both element and target must be defined");null!=this[c].jquery?this[c]=this[c][0]:"string"===typeof this[c]&&(this[c]=document.querySelector(this[c]))}n(this.element,
this.getClass("element"));n(this.target,this.getClass("target"));if(!this.options.attachment)throw Error("Tether Error: You must provide an attachment");this.targetAttachment=m(this.options.targetAttachment);this.attachment=m(this.options.attachment);this.offset=q(this.options.offset);this.targetOffset=q(this.options.targetOffset);null!=this.scrollParent&&this.disable();this.scrollParent="scroll-handle"===this.targetModifier?this.target:d(this.target);if(!1!==this.options.enabled)return this.enable(b)};
b.prototype.getTargetBounds=function(){var a,b,e,d,f,g;if(null!=this.targetModifier)switch(this.targetModifier){case "visible":if(this.target===document.body)return{top:pageYOffset,left:pageXOffset,height:innerHeight,width:innerWidth};a=c(this.target);d={height:a.height,width:a.width,top:a.top,left:a.left};d.height=Math.min(d.height,a.height-(pageYOffset-a.top));d.height=Math.min(d.height,a.height-(a.top+a.height-(pageYOffset+innerHeight)));d.height=Math.min(innerHeight,d.height);d.height-=2;d.width=
Math.min(d.width,a.width-(pageXOffset-a.left));d.width=Math.min(d.width,a.width-(a.left+a.width-(pageXOffset+innerWidth)));d.width=Math.min(innerWidth,d.width);d.width-=2;d.top<pageYOffset&&(d.top=pageYOffset);d.left<pageXOffset&&(d.left=pageXOffset);return d;case "scroll-handle":return f=this.target,f===document.body?(f=document.documentElement,a={left:pageXOffset,top:pageYOffset,height:innerHeight,width:innerWidth}):a=c(f),g=getComputedStyle(f),b=f.scrollWidth>f.clientWidth||"scroll"===[g.overflow,
g.overflowX]||this.target!==document.body,e=0,b&&(e=15),e=a.height-parseFloat(g.borderTopWidth)-parseFloat(g.borderBottomWidth)-e,d={width:15,height:e/f.scrollHeight*e*.975,left:a.left+a.width-parseFloat(g.borderLeftWidth)-15},b=0,408>e&&this.target===document.body&&(b=-1.1E-4*Math.pow(e,2)-.00727*e+22.58),this.target!==document.body&&(d.height=Math.max(d.height,24)),f=this.target.scrollTop/(f.scrollHeight-e),d.top=f*(e-d.height-b)+a.top+parseFloat(g.borderTopWidth),this.target===document.body&&(d.height=
Math.max(d.height,24)),d}else return c(this.target)};b.prototype.clearCache=function(){return this._cache={}};b.prototype.cache=function(a,b){null==this._cache&&(this._cache={});null==this._cache[a]&&(this._cache[a]=b.call(this));return this._cache[a]};b.prototype.enable=function(a){null==a&&(a=!0);n(this.target,this.getClass("enabled"));n(this.element,this.getClass("enabled"));this.enabled=!0;this.scrollParent!==document&&this.scrollParent.addEventListener("scroll",this.position);if(a)return this.position()};
b.prototype.disable=function(){f(this.target,this.getClass("enabled"));f(this.element,this.getClass("enabled"));this.enabled=!1;if(null!=this.scrollParent)return this.scrollParent.removeEventListener("scroll",this.position)};b.prototype.destroy=function(){var a,b,c,e,d;this.disable();d=[];a=c=0;for(e=C.length;c<e;a=++c)if(b=C[a],b===this){C.splice(a,1);break}else d.push(void 0);return d};b.prototype.updateAttachClasses=function(a,b){var c,e,d,f,g,k=this;null==a&&(a=this.attachment);null==b&&(b=this.targetAttachment);
d="left top bottom right middle center".split(" ");null!=(c=this._addAttachClasses)&&c.length&&this._addAttachClasses.splice(0,this._addAttachClasses.length);c=null!=this._addAttachClasses?this._addAttachClasses:this._addAttachClasses=[];a.top&&c.push(""+this.getClass("element-attached")+"-"+a.top);a.left&&c.push(""+this.getClass("element-attached")+"-"+a.left);b.top&&c.push(""+this.getClass("target-attached")+"-"+b.top);b.left&&c.push(""+this.getClass("target-attached")+"-"+b.left);e=[];f=0;for(g=
d.length;f<g;f++)c=d[f],e.push(""+this.getClass("element-attached")+"-"+c);f=0;for(g=d.length;f<g;f++)c=d[f],e.push(""+this.getClass("target-attached")+"-"+c);return y(function(){if(null!=k._addAttachClasses)return h(k.element,k._addAttachClasses,e),h(k.target,k._addAttachClasses,e),k._addAttachClasses=void 0})};b.prototype.position=function(b){var d,f,k,h,m,l,q,n,y,r,B,t,p,v,A,w,C,E,K,F,L=this;null==b&&(b=!0);if(this.enabled){this.clearCache();p=z(this.targetAttachment,this.attachment);this.updateAttachClasses(this.attachment,
p);d=this.cache("element-bounds",function(){return c(L.element)});B=d.width;f=d.height;0===B&&0===f&&null!=this.lastSize?(f=this.lastSize,B=f.width,f=f.height):this.lastSize={width:B,height:f};k=A=this.cache("target-bounds",function(){return L.getTargetBounds()});q=a(x(this.attachment),{width:B,height:f});v=a(x(p),k);h=a(this.offset,{width:B,height:f});m=a(this.targetOffset,k);q=G(q,h);v=G(v,m);k=A.left+v.left-q.left;w=A.top+v.top-q.top;F=u.modules;C=0;for(K=F.length;C<K;C++)if(l=F[C],l=l.position.call(this,
{left:k,top:w,targetAttachment:p,targetPos:A,attachment:this.attachment,elementPos:d,offset:q,targetOffset:v,manualOffset:h,manualTargetOffset:m,scrollbarSize:n}),null!=l&&"object"===typeof l){if(!1===l)return!1;w=l.top;k=l.left}d={page:{top:w,left:k},viewport:{top:w-pageYOffset,bottom:pageYOffset-w-f+innerHeight,left:k-pageXOffset,right:pageXOffset-k-B+innerWidth}};document.body.scrollWidth>window.innerWidth&&(n=this.cache("scrollbar-size",s),d.viewport.bottom-=n.height);document.body.scrollHeight>
window.innerHeight&&(n=this.cache("scrollbar-size",s),d.viewport.right-=n.width);if(""!==(r=document.body.style.position)&&"static"!==r||""!==(t=document.body.parentElement.style.position)&&"static"!==t)d.page.bottom=document.body.scrollHeight-w-f,d.page.right=document.body.scrollWidth-k-B;if(!1!==(null!=(E=this.options.optimizations)?E.moveElement:void 0)&&null==this.targetModifier){y=this.cache("target-offsetparent",function(){return e(L.target)});B=this.cache("target-offsetparent-bounds",function(){return c(y)});
r=getComputedStyle(y);getComputedStyle(this.element);n={};p=["Top","Left","Bottom","Right"];E=0;for(f=p.length;E<f;E++)t=p[E],n[t.toLowerCase()]=parseFloat(r["border"+t+"Width"]);B.right=document.body.scrollWidth-B.left-B.width+n.right;B.bottom=document.body.scrollHeight-B.top-B.height+n.bottom;d.page.top>=B.top+n.top&&d.page.bottom>=B.bottom&&d.page.left>=B.left+n.left&&d.page.right>=B.right&&(t=y.scrollTop,r=y.scrollLeft,d.offset={top:d.page.top-B.top+t-n.top,left:d.page.left-B.left+r-n.left})}this.move(d);
this.history.unshift(d);3<this.history.length&&this.history.pop();b&&g();return!0}};b.prototype.move=function(a){var b,c,d,f,g,h,m,l,n,q,r,p,s=this;if(null!=this.element.parentNode){h={};for(m in a)for(d in h[m]={},a[m]){c=!1;r=this.history;n=0;for(q=r.length;n<q;n++)if(g=r[n],!t(null!=(p=g[m])?p[d]:void 0,a[m][d])){c=!0;break}c||(h[m][d]=!0)}b={top:"",left:"",right:"",bottom:""};g=function(a,c){var d,e;if(!1!==(null!=(d=s.options.optimizations)?d.gpu:void 0)){if(a.top?(b.top=0,e=c.top):(b.bottom=
0,e=-c.bottom),a.left?(b.left=0,d=c.left):(b.right=0,d=-c.right),b[w]="translateX("+Math.round(d)+"px) translateY("+Math.round(e)+"px)","msTransform"!==w)return b[w]+=" translateZ(0)"}else return a.top?b.top=""+c.top+"px":b.bottom=""+c.bottom+"px",a.left?b.left=""+c.left+"px":b.right=""+c.right+"px"};c=!1;(h.page.top||h.page.bottom)&&(h.page.left||h.page.right)?(b.position="absolute",g(h.page,a.page)):(h.viewport.top||h.viewport.bottom)&&(h.viewport.left||h.viewport.right)?(b.position="fixed",g(h.viewport,
a.viewport)):null!=h.offset&&h.offset.top&&h.offset.left?(b.position="absolute",f=this.cache("target-offsetparent",function(){return e(s.target)}),e(this.element)!==f&&y(function(){s.element.parentNode.removeChild(s.element);return f.appendChild(s.element)}),g(h.offset,a.offset),c=!0):(b.position="absolute",g({top:!0,left:!0},a.page));c||"BODY"===this.element.parentNode.tagName||(this.element.parentNode.removeChild(this.element),document.body.appendChild(this.element));l={};c=!1;for(d in b)h=b[d],
a=this.element.style[d],""===a||""===h||"top"!==d&&"left"!==d&&"bottom"!==d&&"right"!==d||(a=parseFloat(a),h=parseFloat(h)),a!==h&&(c=!0,l[d]=b[d]);if(c)return y(function(){return k(s.element.style,l)})}};return b}();u.position=A;this.Tether=k(r,u)}).call(this);(function(){var p,v,l,u,n,G,x,z=[].indexOf||function(l){for(var k=0,g=this.length;k<g;k++)if(k in this&&this[k]===l)return k;return-1};x=this.Tether.Utils;n=x.getBounds;l=x.extend;G=x.updateClasses;v=x.defer;p=["left","top","right","bottom"];
u=function(l,k){var g,c,e,s,d;"scrollParent"===k?k=l.scrollParent:"window"===k&&(k=[pageXOffset,pageYOffset,innerWidth+pageXOffset,innerHeight+pageYOffset]);k===document&&(k=k.documentElement);if(null!=k.nodeType)for(g=c=n(k),e=getComputedStyle(k),k=[g.left,g.top,c.width+g.left,c.height+g.top],g=s=0,d=p.length;s<d;g=++s)c=p[g],c=c[0].toUpperCase()+c.substr(1),k[g]="Top"===c||"Left"===c?k[g]+parseFloat(e["border"+c+"Width"]):k[g]-parseFloat(e["border"+c+"Width"]);return k};this.Tether.modules.push({position:function(p){var k,
g,c,e,s,d,b,a,m,q,A,f,C,w,h,t,r,x,E,F,H,J,I,D=this;h=p.top;a=p.left;p=p.targetAttachment;if(!this.options.constraints)return!0;t=this.cache("element-bounds",function(){return n(D.element)});b=t.height;t=t.width;0===t&&0===b&&null!=this.lastSize&&(b=this.lastSize,t=b.width,b=b.height);w=this.cache("target-bounds",function(){return D.getTargetBounds()});C=w.height;w=w.width;f={};d={};g=[this.getClass("pinned"),this.getClass("out-of-bounds")];r=this.options.constraints;d=0;for(f=r.length;d<f;d++)e=r[d],
e.outOfBoundsClass&&g.push(e.outOfBoundsClass),e.pinnedClass&&g.push(e.pinnedClass);f=0;for(x=g.length;f<x;f++)for(d=g[f],m=["left","top","right","bottom"],r=0,E=m.length;r<E;r++)e=m[r],g.push(""+d+"-"+e);k=[];f=l({},p);d=l({},this.attachment);E=this.options.constraints;r=0;for(x=E.length;r<x;r++){e=E[r];m=e.to;c=e.attachment;A=e.pin;null==c&&(c="");0<=z.call(c," ")?(e=c.split(" "),c=e[0],s=e[1]):s=c;e=u(this,m);if("target"===c||"both"===c)h<e[1]&&"top"===f.top&&(h+=C,f.top="bottom"),h+b>e[3]&&"bottom"===
f.top&&(h-=C,f.top="top");"together"===c&&(h<e[1]&&"top"===f.top&&("bottom"===d.top?(h+=C,f.top="bottom",h+=b,d.top="top"):"top"===d.top&&(h+=C,f.top="bottom",h-=b,d.top="bottom")),h+b>e[3]&&"bottom"===f.top&&("top"===d.top?(h-=C,f.top="top",h-=b,d.top="bottom"):"bottom"===d.top&&(h-=C,f.top="top",h+=b,d.top="top")),"middle"===f.top&&(h+b>e[3]&&"top"===d.top?(h-=b,d.top="bottom"):h<e[1]&&"bottom"===d.top&&(h+=b,d.top="top")));if("target"===s||"both"===s)a<e[0]&&"left"===f.left&&(a+=w,f.left="right"),
a+t>e[2]&&"right"===f.left&&(a-=w,f.left="left");"together"===s&&(a<e[0]&&"left"===f.left?"right"===d.left?(a+=w,f.left="right",a+=t,d.left="left"):"left"===d.left&&(a+=w,f.left="right",a-=t,d.left="right"):a+t>e[2]&&"right"===f.left?"left"===d.left?(a-=w,f.left="left",a-=t,d.left="right"):"right"===d.left&&(a-=w,f.left="left",a+=t,d.left="left"):"center"===f.left&&(a+t>e[2]&&"left"===d.left?(a-=t,d.left="right"):a<e[0]&&"right"===d.left&&(a+=t,d.left="left")));if("element"===c||"both"===c)h<e[1]&&
"bottom"===d.top&&(h+=b,d.top="top"),h+b>e[3]&&"top"===d.top&&(h-=b,d.top="bottom");if("element"===s||"both"===s)a<e[0]&&"right"===d.left&&(a+=t,d.left="left"),a+t>e[2]&&"left"===d.left&&(a-=t,d.left="right");"string"===typeof A?A=function(){var a,b,c,d;c=A.split(",");d=[];b=0;for(a=c.length;b<a;b++)q=c[b],d.push(q.trim());return d}():!0===A&&(A=["top","left","right","bottom"]);A||(A=[]);c=[];m=[];h<e[1]&&(0<=z.call(A,"top")?(h=e[1],c.push("top")):m.push("top"));h+b>e[3]&&(0<=z.call(A,"bottom")?(h=
e[3]-b,c.push("bottom")):m.push("bottom"));a<e[0]&&(0<=z.call(A,"left")?(a=e[0],c.push("left")):m.push("left"));a+t>e[2]&&(0<=z.call(A,"right")?(a=e[2]-t,c.push("right")):m.push("right"));if(c.length)for(s=null!=(J=this.options.pinnedClass)?J:this.getClass("pinned"),k.push(s),H=0,F=c.length;H<F;H++)e=c[H],k.push(""+s+"-"+e);if(m.length)for(s=null!=(I=this.options.outOfBoundsClass)?I:this.getClass("out-of-bounds"),k.push(s),H=0,F=m.length;H<F;H++)e=m[H],k.push(""+s+"-"+e);if(0<=z.call(c,"left")||0<=
z.call(c,"right"))d.left=f.left=!1;if(0<=z.call(c,"top")||0<=z.call(c,"bottom"))d.top=f.top=!1;f.top===p.top&&f.left===p.left&&d.top===this.attachment.top&&d.left===this.attachment.left||this.updateAttachClasses(d,f)}v(function(){G(D.target,k,g);return G(D.element,k,g)});return{top:h,left:a}}})}).call(this);(function(){var p,v,l,u;u=this.Tether.Utils;v=u.getBounds;l=u.updateClasses;p=u.defer;this.Tether.modules.push({position:function(n){var u,x,z,y,k,g,c,e,s,d,b,a,m,q=this;c=n.top;y=n.left;g=this.cache("element-bounds",
function(){return v(q.element)});n=g.height;g=g.width;e=this.getTargetBounds();z=c+n;k=y+g;n=[];if(c<=e.bottom&&z>=e.top)for(m=["left","right"],s=0,a=m.length;s<a;s++)g=m[s],(d=e[g])!==y&&d!==k||n.push(g);if(y<=e.right&&k>=e.left)for(k=["top","bottom"],d=0,y=k.length;d<y;d++)g=k[d],(b=e[g])!==c&&b!==z||n.push(g);x=[];u=[];c=["left","top","right","bottom"];x.push(this.getClass("abutted"));b=0;for(e=c.length;b<e;b++)g=c[b],x.push(""+this.getClass("abutted")+"-"+g);n.length&&u.push(this.getClass("abutted"));
c=0;for(b=n.length;c<b;c++)g=n[c],u.push(""+this.getClass("abutted")+"-"+g);p(function(){l(q.target,u,x);return l(q.element,u,x)});return!0}})}).call(this);(function(){this.Tether.modules.push({position:function(p){var v,l,u;u=p.top;v=p.left;if(this.options.shift)return p=function(l){return"function"===typeof l?l.call(this,{top:u,left:v}):l},l=p(this.options.shift),"string"===typeof l?(l=l.split(" "),l[1]||(l[1]=l[0]),p=l[0],l=l[1],p=parseFloat(p,10),l=parseFloat(l,10)):(l=[l.top,l.left],p=l[0],l=
l[1]),u+=p,v+=l,{top:u,left:v}}})}).call(this);return this.Tether});
